### ISSUE TITLE
Use Access Token instead of Kubeconfig File

### ISSUE THREAD

**Issue by ViniciusSouza** [allantargino/ContainerNanny#4]
As the Container Nanny runs inside the cluster we can use the access token rather than the kubeconfig file.

**Comment by allantargino** [comment]
References:
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
* https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
* https://kubernetes.io/docs/reference/access-authn-authz/authorization/#a-quick-note-on-service-accounts
